[package]
name = "solana-test"
version = "0.1.1"
edition = "2021"

[dependencies]
solana-program = "1.17.17"
borsh = "0.9.1"
borsh-derive = "0.9.1"

[lib]
name = "solana_test"
crate-type = ["cdylib", "lib"]
